Added additional problems
vnbrs/hackerrank-sql pull request #1
Opened 2019-07-25 00:56 UTC by dhayalramk

Added additional problems which are unsolved or recent one.

2019-07-28 04:42 UTC, dhayalramk commented
@vnbrs  Is it possible to merge the solutions of SQL!.

2019-07-29 16:02 UTC, vinibrsl requested changes

2019-07-29 16:02 UTC, vnbrs commented on README.md
> +* [Advanced Join](https://github.com/vnbrs/hackerrank-sql/tree/master/advanced-join) - WIP
```suggestion
* [Advanced Join](https://github.com/vnbrs/hackerrank-sql/tree/master/advanced-join)
```

2019-07-29 16:02 UTC, vnbrs commented on README.md
> +* [Alternative Queries](https://github.com/vnbrs/hackerrank-sql/tree/master/alternative-queries) - WIP
```suggestion
* [Alternative Queries](https://github.com/vnbrs/hackerrank-sql/tree/master/alternative-queries)
```

2019-07-29 16:03 UTC, vnbrs commented
Hi @dhayalramk. Thank you for your contribution.

I left 2 suggestions so we can merge your PR. Please accept them and then I'll merge it.

2019-07-30 16:33 UTC, dhayalramk commented
@vnbrs  I accepted the suggestions  :) If anything pending my side, Please let me know.

2019-08-01 14:10 UTC, merged

2019-08-01 14:10 UTC, vnbrs commented
Merged! Thanks.